### ISSUE TITLE
Incorrect classpath in ReadMe file

### ISSUE THREAD

**Issue by philgooch** [tapstream/rollbar-logback#2]
I think the Readme should specify

appender name="ROLLBAR" class="com.tapstream.rollbar.RollbarAppender"

as in https://github.com/tapstream/rollbar-logback/blob/master/example/logback.xml.example

rather than

appender name="ROLLBAR" class="com.tapstream.rollbar.logback.RollbarAppender"

**Comment by nsitarz** [comment]
Fixed in 6680948790849765fe795b2d81c71b48f6874228
